AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    DynamoName:
        Type: String
    DynamoKey:
        Type: String
      
Resources:
  DynamoLabDiego:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoKey
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoKey
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
Outputs:
  DynamoName:
      Value: !Ref DynamoLabDiego
      Export:
        Name: DynamoLabDiego
  DynamoNameArn:
      Value: !GetAtt DynamoLabDiego.Arn
      Export:
        Name: DynamoLabDiegoArn